### PR TITLE
Entrypoint filename correction

### PR DESCRIPTION
**Pull request by AlexAndrascu**

### CODE REVIEW

**Comment by AsavarTzeth** [comment]
I would have expected a comment in the pull request, not only in the commit. But that is just my preference.

Permissions fail because git or github does not appear to save my local permissions. I am still unsure about how this works to be honest. I still have a lot to learn to be honest.

**Comment by AsavarTzeth** [comment]
Looking at that entrypoint file. Yes, I would probably simply that a great deal if I had made this recently.

Is there anything else you need for this to serve you better? I will consider prioritizing this again if someone has use for it.

**Comment by AsavarTzeth** [comment]
This looks good enough. I don't know why I felt the need to consider this further. I will merge this right away.

**Comment by AlexAndrascu** [comment]
Hi Patrik,
Thanks for getting back to me on this and sorry for not commenting in the right place. It was sort of late in the night and I'm a bit new on github as well. Not very knowledgeable in how the github pull request system works. 

 So far this is the best dockerfile I've found based on debian:wheezy and with some minor adjustments I'm planing to use it. 

One thing I'm trying to solve now is adding the ENV variables for the MySQL / MariaDB container into the php configuration. 

This is what I've found so far:
https://github.com/dubture-dockerfiles/nginx-php/blob/master/startup.sh

Do you have any other ideeas on how may we accomplish this?

Alex

**Comment by AsavarTzeth** [comment]
Yes and sorry for any confusion I have caused. I am having a really bad day and don't know what I am doing at the moment to be truthful. I have a tendency to panic in certain social situations. Again please forgive me.

I am happy you find this image useful. I will probably take another look into it and intigrate what I have learned these past months, to further improve it.

**Comment by AlexAndrascu** [comment]
That would be brilliant ! Thanks ! Shall I open an issue about that ?

**Comment by AsavarTzeth** [comment]
No Github seems to automatically close these issues, when they are merged. We can continue any discussion here for now. Unless there is a new thing for you to pull request of course :)

**Comment by AlexAndrascu** [comment]
Cool! We'll do that.

**Comment by AsavarTzeth** [comment]
Thanks for being understanding. It really brightened my mood, probably saved my day.

**Comment by AsavarTzeth** [comment]
If I understand things correctly. Your current approach is to run nginx and php5 in the same container and you wish to change this into the Docker single process per container approach? If not, what role does my image play in your project? Please elaborate.

Regarding adding the MySQL ENV variables to the php configuration. As I assume you know, docker shares them when you link containers. You should simply need to check if they are set, then edit any lines you need in the php config, using the value of the MySQL env var.

I admit I am a bit slow today, and it often takes a bit of time and testing before I can understand someone else's logic. I think the best approach is if you tell me exactly what you are attempting, then I will test run your work. This is usually the fastest way for me to understand things.

**Comment by AlexAndrascu** [comment]
Hi Patrik,

No, my current approach is to use 3 different containers, 
1. The official nginx ( FROM nginx )
2. This for MariaDB https://github.com/AlexAndrascu/docker-mariadb
3. And finally yours for php

This is how I run them:
  `sudo docker run -d -e USER=alex -e PASS=password --volumes-from mariadb-data --name mysql -p   3306:3306 intellixweb/mariadb`

`sudo docker run --link mysql:db -v /var/www:/var/www:rw -v /var/run -p 80:80 -d --name lempp nginx`

`sudo docker run --name php5 --link mysql:db --volumes-from lempp -e PHP5_FPM_LISTEN=/var/run/php5-fpm.sock -e PHP5_FPM_LOG_LEVEL=debug -d php5-fpm`

The problem I have is that I need to get the mysql port and ip in my php files. 
They exist as linux ENV variables but in order to get them in PHP if i understand correcty we need to:
1. Set the variable_orders to EGPCS in php.ini as per http://php.net/manual/en/ini.core.php#ini.variables-order
2. Add this variables to pool.d/www.conf like:

`; Pass environment variables like LD_LIBRARY_PATH. All $VARIABLEs are taken from
; the current environment.
; Default Value: clean env
;env[HOSTNAME] = $HOSTNAME
;env[PATH] = /usr/local/bin:/usr/bin:/bin
;env[TMP] = /tmp
;env[TMPDIR] = /tmp
;env[TEMP] = /tmp
`

**Comment by AlexAndrascu** [comment]
Actually there are 4 containers but one of them is a Data Volume Container called mariadb-data.

**Comment by AsavarTzeth** [comment]
Yes I figured as much. I too would not count data storage, since that does not affect things.

I have to admit point 1. is mostly outside my knowledge. I am self educated and have not had a need to learn everything in php5 configuration yet.

As for the core issue. Am I correct in assuming you have the data (from ENV vars provided by Docker link), but you have not been able to apply it? and/or you would like this functionality in the entrypoint script?

I am sorry if I sound like some customer support simpleton or something. Really, I now wish I had spent more time on this.

**Comment by AsavarTzeth** [comment]
After reading a bit on the topic. You need me to set `; variables_order: "EGPCS"` (omitting ";" of course) in php.ini, while the typical & default value is GPCS.

The issue to me here is, I need to read up and understand this setting. Since my knowledge is limited I am very cautions when it comes to any security/performance implications I might not know about.

**Comment by AlexAndrascu** [comment]
I have now created another pull request for this. 
Off course 2 set of eyes is better then 1. For now I'm going to use it as it's only my local but generally I'm looking to make it production ready as soon as possible. 
I agree we need to understand the implications of the variables_order but I don't think it's too complex to be honest. 
Plus setting the variables order to EGPCS is not enough as you still need to declare specifically which ENV variables are used.

**Comment by AlexAndrascu** [comment]
Everyone else seems to follow the same approach:

https://github.com/tutumcloud/tutum-docker-php/blob/master/Dockerfile

But again if you can think of a better way to do this I want to hear about it.

**Comment by AsavarTzeth** [comment]
Yes, I already suspect it is a tiny performance hit and nothing more.

And no, I cannot think of a better way at this time. I trust your judgment here and tutum is usually reliable as well. To be honest I suspect this might have been the cause of my own issues in the past. But I could not solve it back then, since I did not fully understand it.

We could always add this as another branch at this time and use it for our own purposes. I need to add a dev or beta branch to this repo anyways, since I use the docker hub build triggers.

**Pull request merged**
